server:
  port : 8084
  
spring:
  datasource:
    #url: jdbc:h2:file:./camunda-h2-database
    url: jdbc:h2:mem:camunda-h2-database
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console.enabled: true

camunda.bpm.admin-user:
  id: admin
  password: admin
  
scheduler:
  fixedRate: 500
  initialDelay: 60000  